# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.CharField(default='Family time!', max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_per_round',
            field=models.DurationField(default='0:01:00'),
        ),
    ]
