# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20161223_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_per_round',
            field=models.IntegerField(default='60000'),
        ),
    ]
