# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20161223_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='time_per_round',
            field=models.IntegerField(choices=[(30000, ':30'), (45000, ':45'), (60000, '1:00'), (90000, '1:30')], default=60000),
        ),
        migrations.AddField(
            model_name='word',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
