# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20161224_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
