# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20161224_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='submissions',
        ),
    ]
